from pages import *
from links import Links


class TestSuite:

    driver = webdriver.Chrome("driver\\chromedriver.exe")

    @classmethod
    def setup_class(cls):
        cls.driver.maximize_window()
        cls.driver.get(Links.main_page)

    @classmethod
    def teardown_class(cls):
        cls.driver.quit()

    def test_login(self):
        """
        Авторизация на портале
        """
        page = LoginPage(self.driver)
        page.username("Test1")
        page.password("123")
        page.submit()
        page.wait.text_appear("Бухгалтерский учет")

    def te1st_getting_cash_request(self):
        page = CashPullRequestPage(self.driver)
        page.scroll_to_bottom()
        page.click_by_text("Заявка на получение наличных денег")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        # Реквизиты документа
        page.new_document.account_number("ПАО")
        page.new_document.tracking_number("1233")
        page.new_document.operation("Снятие наличных (деньги в пути) (Все КОСГУ)")
        # Информация о документе
        page.new_document.document_number("88005553535")
        page.new_document.document_date("14.09.2017")
        page.new_document.entry_date("14.09.2017")
        page.new_document.deadline("24.09.2017")
        page.new_document.click_by_text("Дополнительно")
        # Доверенность
        page.new_document.trustee("Попов В.А.")
        page.new_document.trustee_name_dative_case("Попову В.А.")
        page.new_document.trustee_position("Советник")
        page.new_document.trustee_position_dative_case("Советнику")
        page.new_document.foundation("Основание")
        # Чек
        page.new_document.check_series("ME")
        page.new_document.check_number("12333333")
        page.new_document.check_date("12.09.2017")
        page.new_document.check_valid_till("12.09.2018")
        # Подписывающие лица
        page.new_document.manager("Портная Н.О.")
        page.new_document.chief_accountant("Дорофеева Т.Н.")
        page.new_document.click_by_text("Строки документа")
        page.new_document.click_by_text("Добавить")
        page.new_document.click_by_text("Новую строку")
        page.new_document.new_line.kbk("110 1 11 02012 01 0000 120")
        page.new_document.new_line.kbk_type("Группировочный КБК (гКБК)")
        page.new_document.new_line.kosgu("110")
        # page.new_document.new_line.costs_type("")
        page.new_document.new_line.operation("Снятие наличных (деньги в пути) (Все КОСГУ)")
        page.new_document.new_line.funds_source("1 - Средства бюджета")
        page.new_document.new_line.cash_transaction_code("53 Прочие выдачи")
        page.new_document.new_line.code_goal("123334")
        page.new_document.new_line.payment_purpose("Назначение")
        page.new_document.new_line.amount("2300000")
        page.new_document.new_line.comment("Примечание")
        page.new_document.new_line.click_by_text("Сохранить", 2)
        page.new_document.click_by_text("Сохранить")
        page.new_document.click_by_text("Закрыть", 2)
        page.new_document.click_by_text("Закрыть")
        page.filter("88005553535")
        page.click_by_text("Печать")
        page.click_by_text("Действие")
        page.click_by_text("Провести")
        page.holding_request.lddate_prov("12.09.2017")
        page.holding_request.typical_operation("Снятие наличных (деньги в пути) (Все КОСГУ)")
        page.holding_request.submit()
        page.click_by_text("Закрыть")
        page.wait.array_error()

    def te1st_pko(self):
        # ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ Информация о документе
        print("ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ Информация о документе")
        page = PKOPage(self.driver)
        page.scroll_to_bottom()
        page.click_by_text("Приходный кассовый ордер")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page.set_select2_wl("documentKind", "Приходный кассовый ордер", "поле Вид документа")
        page.set_text_wl("documentNumber", "2", "Номер")
        # ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ Принято от
        print("ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ Принято от")
        page.set_select2_wl("employee", "Петров А.В.", "Сотрудник")
        page.set_select2_wl("organization", "МИФНС России № 46", "Организация", exactly=False)
        assert page.checker.check_text_input("receivedFrom", " УФК по г. Москве (МИФНС России № 46 по г.Москве)")
        page.set_select2_wl("operation", "Получение наличных в кассу", "Типовая операция")
        page.set_select2_wl("departmentUnit", "ФАМИРТ", "Группа учета")
        page.set_text_wl("cashReportNumber", "25", "Номер кассового отчета")
        page.set_text_wl("foundation", "Текст заполнения поля Основание", "Основание")
        # ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Строки документа
        print("ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Строки документа")
        page.click_by_text("Строки документа")
        page.line.click_by_text("Добавить")
        page.line.click_by_text("Новую строку")
        sleep(2)
        page.line.set_select2_wl("operation",
                                 "Получение наличных в кассу", "Типовая операция", order=2)
        page.line.set_select2_wl("kosgu", "290", "КОСГУ", exactly=False)
        page.line.set_select2_wl("inventory", "TV кабель", "Номенклатура")
        page.line.set_select2_wl("kbk", "(2017) - Больницы", "КБК", exactly=False)
        page.line.set_select2_wl("expenseType", "Прочие расходы", "Вид затрат")
        page.line.set_text_wl("quantity", "20", "Количество")
        page.line.set_text_wl("amount", "100", "Сумма", order=2)
        page.line.set_text_wl("ndsPercent", "18", "Ставка НДС")
        assert page.checker.check_text_input("amountWithoutNds", "84,75")
        assert page.checker.check_text_input("ndsAmount", "15,25")
        page.line.set_select2_wl("departmentUnit", "ФАМИРТ", "Группа учета", order=2)
        page.line.set_select2_wl("recepient", "Зотова М.В.", "Получатель (МОЛ)")
        page.line.set_text_wl("comment", "Текст заполнения поля Комментарий", "Комментарий", order=2)
        page.line.set_select2_wl("act", "2008 - Договор", "Мероприятие")
        page.line.set_select_wl("CashTransactionCode", "53 Прочие выдачи", "Кассовый символ")
        sleep(2)
        page.line.click_by_text("Сохранить", 2)
        # ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Приложение
        print("ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Приложение")
        page.click_by_text("Приложение")
        # ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Проводки
        print("ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Проводки")
        page.click_by_text("Проводки")
        # ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Строки документа
        print("ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР \ блок Строки документа")
        page.click_by_text("Строки документа")
        # page.accounting.save_screenshot("test1", default_folder="C:\\Test\\")
        sleep(5)
        page.line.click_by_text("Сохранить")
        page.wait.array_error()
        assert page.wait.text_appear("Документ сохранен")
        print("ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР - ДОКУМЕНТ СОХРАНЕН")
        page.click_by_text("Закрыть")

    def te1st_rko(self):
        # Расходный КАССОВЫЙ ОРДЕР \ Информация о документе
        print("Расходный КАССОВЫЙ ОРДЕР \ Информация о документе")
        page = PKOPage(self.driver)
        page.scroll_to_bottom()
        page.click_by_text("Расходный кассовый ордер")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page.set_select2_wl("documentKind", "Расходный кассовый ордер", "поле Вид документа")
        page.set_text_wl("documentNumber", "2", "Номер")
        page.set_date_wl("documentDate", "05.02.2018")
        page.set_date_wl("entryDate", "05.02.2018", "Дата проводки")
        page.set_select2_wl("OperationMaster", "Выплата заработной платы из кассы", "Типовая операция")
        page.set_select2_wl("departmentUnit", "ФАМИРТ", "Группа учета")
        page.set_text_wl("foundation", "Тест", "Основание")
        page.set_text_wl("cashReportNumber", "25", "Номер кассового отчета")
        page.set_select2_wl("employee", "Петров А.В.", "Сотрудник")
        sleep(2)
        page.set_select2_wl("counterparty", 'ПАО "МегаФон"', "Организация")
        sleep(5)
        print("Расходный КАССОВЫЙ ОРДЕР \ блок Строки документа")
        page.click_by_text("Строки документа")
        page.line.click_by_text("Добавить")
        page.line.click_by_text("Новую строку")


        page.wait.array_error()

    def te1st_zkr(self):
        # ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Информация о документе
        print("ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Информация о документе")
        page = ZKRPage(self.driver)
        page.scroll_to_bottom()
        page.click_by_text("Заявка на кассовый расход")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page.set_select2_wl("documentKind", "Заявка на кассовый расход", "поле Вид документа")
        page.set_select2_wl("accountDetails", "14481000320 (Московская обл.)", exactly=False)
        page.set_select2_wl("counterparty", "МИФНС России № 46", "Наименование контрагента или ФИО", exactly=False)
        page.set_text_wl("documentNumber", "3")
        page.set_text_wl("ofkNumber", "77", "Номер УФК")
        assert page.checker.check_text_select("counterpartyAccountDetails", "40101810800000010041")
        sleep(5)
        page.set_date_wl("documentDate", "05.02.2018")
        page.set_date_wl("entryDate", "05.02.2018", "Дата проводки")
        page.set_date_wl("limitDate", "10.02.2018", "Предельная дата исполнения")
        page.set_select2_wl("operation", "(226) Оплата за прочие услуги", "Типовая операция")
        # ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Реквизиты документа
        print("ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Реквизиты документа")
        page.request.click_by_text("Реквизиты документа")
        page.request.set_select2_wl("currency", "Российский рубль", "Код валюты по ОКВ")
        page.request.set_select2_wl("departmentUnit", "ФАМИРТ", "Группа учета")
        page.request.set_select2_wl("faip", "Технопарк МФТИ, поселок Северный", "Код объекта по ФАИП")
        page.request.set_text_wl("priority", "1", "Приоритет исполнения")
        page.request.set_select_wl("paymentForm", "4 – срочно", "Вид платежа")
        page.request.set_text_wl("paymentPurpose", "Текст заполнения поля Назначение платежа", "Назначение платежа")
        # ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Документ-основание
        print("ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Документ-основание")
        page.doc.click_by_text("Документ-основание")
        page.doc.set_select2_wl("foundation", "", "Документ-основание")
        page.doc.set_text_wl("trackingNumber", "8", "Учетный номер обязательства")
        page.doc.set_select2_wl("documentFoundaiontKind", "Договор", "Вид документ-основания")
        page.doc.set_text_wl("documentFoundationNumber", "25", "Учетный номер обязательства")
        page.doc.set_date_wl("documentFoundationDate", "05.02.2018")
        page.doc.set_text_wl("documentFoundationSubject", "Текст заполнения поля Предмет", "Предмет")
        # ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Расшифровка заявки
        print("ЗАЯВКА НА КАССОВЫЙ РАСХОД \ Расшифровка заявки")
        page.click_by_text("Расшифровка заявки")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page.bid.set_select_wl("activityKind", "1 - Средства бюджета", "Вид стредств")
        page.bid.set_select2_wl("operation", "(226) Оплата за прочие услуги", "Типовая операция", order=2)
        page.bid.set_select2_wl("kbk", "(2016) 122 ЦА Командировки 212,222,226",
                                "КБК плательщика", exactly=False, order=2)
        page.bid.set_select_wl("drawee_kbk_type", "Группировочный КБК (гКБК)", "Тип КБК плательщика", order=2)
        page.bid.set_select2_wl("kosgu", "226", "КОСГУ", exactly=False)
        page.bid.set_select2_wl("costElement", "Прочие услуги", "Вид затрат")
        page.bid.set_text_wl("amountWithoutNds", "100", "Сумма без НДС", order=2)
        page.bid.set_text_wl("ndsPercent", "18", "Ставка НДС")
        page.bid.set_text_wl("ndsAmount", "15,25", "Сумма НДС", order=2)
        page.bid.set_text_wl("amount", "84,75", "Сумма в рублях", order=2)
        # assert page.checker.check_text_input("amountWithoutNds", "84,75")
        # assert page.checker.check_text_input("ndsAmount", "15,25")
        page.bid.set_select2_wl("recepientKbk", "РАГС", "КБК получателя")
        # page.set_text_wl("outstandingPaymentDocumentAmount", "100.00","поле Сумма в рублях")
        # page.set_text_wl("ndsPercent", "18","Ставка НДС")
        # assert page.check_text_input("ndsAmount", "15,25")

    def te1st_znv(self):
        # ЗАЯВКА НА ВОЗВРАТ \ шапка документа
        print("ЗАЯВКА НА ВОЗВРАТ \ шапка документа")
        page = ZNVPage(self.driver)
        page.scroll_to_bottom()
        page.click_by_text("Заявка на возврат")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page.set_text_wl("documentNumber", "1", "Номер")
        page.set_date_wl("documentDate", "05.02.2018", "Дата")
        page.set_select2_wl("accountDetails", "14481000320 (Московская обл.)", "поле Лицевой счет", exactly=False)
        page.set_select2_wl("recepient", "", "Наименование получателя")
        # exactly=False исп. для точного совпадения
        page.set_text_wl("ofkRegistrationNumber", "05.02.2018", "Номер УФК")
        page.set_date_wl("entryDate", "05.02.2018", "Дата проводки")
        page.set_select2_wl("operation",
                            "Выбытие средств из временного распоряжения", "Типовая операция", exactly=False)
        page.set_select2_wl("recepientAccountDetails", "", "Банковский счет")
        page.set_select2_wl("documentKind", "Внебанковская заявка на возврат", "Вид документа")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки")
        page.click_by_text("Расшифровка заявки")
        page.request.set_text_wl("outstandingPaymentDocumentAmount", "100.00", "поле Сумма в рублях")
        page.set_text_wl("ndsPercent", "18", "Ставка НДС")
        page.request.set_text_wl("ndsAmount", "", "Сумма НДС")
        # расчетное значение
        page.request.set_select2_wl("kbk", "0410 9970092041 244", "КБК", exactly=False)
        page.request.set_select_wl("kbkType", "Группировочный КБК (гКБК)", "Тип КБК")
        page.request.set_select2_wl("kosgu", "290", "КОСГУ", exactly=False)
        page.request.set_select2_wl("costElement", "Прочие расходы", "Вид затрат")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Дополнительные реквизиты
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Дополнительные реквизиты")
        page.request.set_text_wl("goalCode", "32", "Код цели")
        page.request.set_select2_wl("investmentProgram", "Технопарк МФТИ, поселок Северный", "Код объекта по ФАИП")
        page.request.set_select2_wl("oktmo", "40 333 000", "Код по ОКТМО", exactly=False)
        page.request.set_select2_wl("expenditureGoalAct", "2008 - Договор", "Мероприятие")
        page.request.set_select2_wl("department", "Договор подряда", "Группа учета")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Информация о платеже
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Информация о платеже")
        page.request.set_text_wl("paymentPurpose", "Текст заполнения поля Назначения платежа", "Назначение платежа")
        page.request.set_select_wl("paymentForm", "4 – срочно", "Вид платежа")
        page.request.set_text_wl("paymentPriority", "1", "Очередность платежа")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Документ-основание
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Документ-основание")
        page.request.set_select2_wl("documentFoundationKind", "Акт выполненных работ", "Вид документа-основание")
        page.request.set_text_wl("documentFoundationNumber", "21", "Номер документа-основание")
        page.request.set_date_wl("documentFoundationDate", "05.02.2018", "Дата документа-основания")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Реквизиты получателя
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки \ блок Реквизиты получателя")
        page.request.set_select2_wl("recepientKbk", "РАГС", "КБК получателя")
        page.request.set_select2_wl("recepientOktmo", "город Москва", "Код по ОКТМО Получателя", exactly=False)
        # page.request.save_screenshot("test1", default_folder="C:\\Test\\")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Документ по зачислению невыясненного платежа
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Документ по зачислению невыясненного платежа")
        page.click_by_text("Документ по зачислению невыясненного платежа")
        page.doc.set_text_wl("outstandingPaymentDocumentNumber", "1", "Номер")
        page.doc.set_date_wl("outstandingPaymentDocumentDate", "05.02.2018", "Дата")
        page.doc.set_text_wl("amount", "100.00", "поле Сумма")
        page.doc.set_text_wl("outstandingPaymentDocumentInn", "111", "поле ИНН")
        page.doc.set_text_wl("outstandingPaymentDocumentKpp", "222", "поле КПП")
        # page.doc.save_screenshot("test1", default_folder="C:\\Test\\")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Уполномоченные сотрудники
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Уполномоченные сотрудники")
        page.click_by_text("Уполномоченные сотрудники")
        page.workers.set_select2_wl("chief", "Е.Ю.Петрова", "Руководитель (уполномоченное лицо)", exactly=False)
        page.workers.set_select2_wl("chiefAccountant", "С.В. Васина", "Код по ОКТМО Получателя", exactly=False)
        # page.workers.save_screenshot("test1", default_folder="C:\\Test\\")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Проводки
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Проводки")
        page.click_by_text("Проводки")
        # page.accounting.save_screenshot("test1", default_folder="C:\\Test\\")
        # ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки
        print("ЗАЯВКА НА ВОЗВРАТ \ закладка Расшифровка заявки")
        page.click_by_text("Расшифровка заявки")
        page.request.click_by_text("Сохранить")
        assert page.wait.text_appear("Документ сохранен")
        # assert "" in self.driver.page_source
        print("ЗАЯВКА НА ВОЗВРАТ - ДОКУМЕНТ СОХРАНЕН")
        sleep(10)

    def test_income_cash_order(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Приходный кассовый ордер")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = IncomingOrderPage(self.driver)
        page.document_kind('value')
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.employee('value')
        page.organization('value')
        page.received_from('value')
        page.operation('value')
        page.department_unit('value')
        page.cash_report_number('value')
        page.foundation('value')
        page = IncomingOrderAddLinePage(self.driver)
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page.operation("value")
        page.kbk("value")
        page.kosgu("value")
        page.expense_type("value")
        page.amount("value")
        page.nds_percent("value")
        page.comment("value")
        page.recepient('value')
        page.click_by_text("Сохранить", 2)
        page = IncomeCashOrderPlusPage(self.driver)
        page.click_by_text("Приложение")
        page.document_foundation('value')
        page.advance_report('value')
        page.comment('value')
        page.chief_accountant('value')
        page.cashier('value')
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_account_cash_warrant(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Расходный кассовый ордер")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = AccountCashWarrantPage(self.driver)
        page.document_kind("Расходный кассовый ордер на аванс")
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.department_unit('value')
        page.operation_master('value')
        page.employee('value')
        page.foundation('value')
        page.cash_report_number('value')
        # Добавили  строку
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = AccountCashWarrantPageAddLine(self.driver)
        page.operation('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.department_unit('value')
        page.sender('value')
        page.material_inventory('value')
        page.quantity('value')
        page.amount('value')
        page.comment('value')
        page.act('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Приложение")
        page = AccountCashWarrantPagePlusPage(self.driver)
        page.document_foundation('value')
        page.advance_report('value')
        page.supplement('value')
        page.accountant('value')
        page.chief('value')
        page.cashier('value')
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_application_for_cash_withdrawal(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Заявка на получение наличных денег")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = ApplicationForCashWithdrawalPage(self.driver)
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.deadline('value')
        page.account_details('value')
        page.tracking_number('value')
        page.operation_master('value')
        # Вкладка дополнительно
        page.click_by_text("Дополнительно")
        page.trustee('value')
        page.trustee_name_dative_case('value')
        page.trustee_position('value')
        page.trustee_position_dative_case('value')
        page.checker.check_text_input("trusteePassport", 'value')
        page.check_series('value')
        page.check_number('value')
        page.check_date('value')
        page.check_valid_till('value')
        page.chief('value')
        page.accountant_general('value')
        page.foundation('value')
        sleep(5)
        # Добавляем строку документа
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = ApplicationForCashWithdrawalAddLinePage(self.driver)
        page.operation_master('value')
        page.kbk_type('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.department_unit('value')
        page.act('value')
        page.code_goal('value')
        page.funds_source('value')
        page.cash_transaction_code('value')
        page.amount('value')
        page.payment_purpose('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_applying_for_card(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Заявка на получение денежных средств, перечисляемых на карту")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = ApplyingForCardPage(self.driver)
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.operation_master('value')
        page.account_details('value')
        page.tracking_number('value')
        page.activity_kind('value')
        # Вкладка Дополнительно
        page.click_by_text("Дополнительно")
        page.card_number('value')
        page.trustee('value')
        page.employee_position('value')
        page.investment_program('value')
        page.employee_name_in_ablative_case('value')
        page.employee_position_in_ablative_case('value')
        page.foundation('value')
        # Вкладка Уполномоченные лица
        page.click_by_text("Уполномоченные лица")
        page.chief('value')
        page.accountant_general('value')
        page.click_by_text("Проводки")
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = ApplyingForCardAddLinePage(self.driver)
        page.operation_master('value')
        page.kbk('value')
        page.kbk_type('value')
        page.kosgu('value')
        page.cost_element('value')
        page.amount('value')
        page.goal_code('value')
        page.department_unit('value')
        page.act('value')
        page.payment_purpose('value')
        page.comment('value')
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_decoding_amounts_unused_funds(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Расшифровка сумм неиспользованных средств")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = DecodingAmountsUnusedFundsPage(self.driver)
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.card_number('value')
        page.operation_type('value')
        page.personal_account('value')
        page.operation_master('value')
        page.tracking_number('value')
        page.investment_program('value')
        # Вкладка Уполномоченные лица
        page.click_by_text("Уполномоченные лица")
        page.chief('value')
        page.accountant_general('value')
        # Вкладка Расшифровка заявки
        page.click_by_text("Расшифровка заявки")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = DecodingAmountsUnusedFundsAddLinePage(self.driver)
        page.operation_master('value')
        page.kosgu('value')
        page.cost_element('value')
        page.kbk('value')
        page.kbk_type('value')
        page.activity_kind('value')
        page.amount('value')
        page.goal_code('value')
        page.department_unit('value')
        page.act('value')
        page.comment('value')
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_application_cash_flow(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page = ApplicationCashFlowPage(self.driver)
        page.click_by_text("Заявка на кассовый расход")
        page.select_month("Январь", "2018")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        sleep(1)
        page.documen_type('value')
        page.number('value')
        page.date('value')
        page.entry_date('value')
        page.limit_date('value')
        page.personal_account('value')
        page.recipient('value')
        page.bank_account_number('value')
        page.number_ufk('value')
        page.operation('value')
        # Заполнение вкладки Реквизиты документа
        page.click_by_text("Реквизиты документа")
        page.currency('value')
        page.department_unit('value')
        page.investment_program('value')
        page.priority('value')
        page.is_advance('value')
        page.priority_of_payment('value')
        page.payment_type('value')
        page.payment_purpose("paymentPurpose- Test")
        # Заполнение вкладки документ основание
        page.click_by_text("Документ-основание")
        page.is_employee('value')
        page.employee('value')
        page.imprest_foundation('value')
        page.advance_report('value')
        page.foundation('value')
        page.tracking_number('value')
        page.document_foundaiont_kind('value')
        page.document_foundation_number('value')
        page.document_foundation_date('value')
        page.document_foundation_subject('value')
        page.checker.check_text_select("documentFoundaiontKind", 'value')
        page.checker.check_text_input("documentFoundationNumber", 'value')
        page.checker.check_text_input("documentFoundationSubject", 'value')
        page.checker.check_text_input("documentFoundationDate", 'value')
        # Расшифровка заявки - добавление строки
        page.click_by_text("Расшифровка заявки")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = DecodingOfTheApplicationPage(self.driver)
        page.activity_kind('value')
        page.operation('value')
        page.kbk('value')
        page.drawee_kbk_type('value')
        page.kosgu('value')
        sleep(5)
        page.cost_element('value')
        page.amount('value')
        page.nds_percent('value')
        page.recepient_kbk('value')
        page.recepient_kbk_type('value')
        page.department('value')
        page.expenditure_goal_act('value')
        page.document_foundation_counterparty('value')
        page.foundation('value')
        page.payment_purpose('value')
        page.comment('value')
        page.checker.check_text_input("amountWithoutNds", 'value', 2)
        page.checker.check_text_input("ndsAmount", 'value', 2)
        page.click_by_text("Сохранить", 2)
        # Реквизиты документов-оснований
        page.click_by_text("Реквизиты документов-оснований")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = ApplicationCashFlowRequisitesPage(self.driver)
        page.document('value')
        page.document_type('value')
        page.document_number('value')
        page.document_date('value')
        page.subject('value')
        page.click_by_text("Сохранить", 2)
        # Реквизиты налоговых платежей
        page.click_by_text("Реквизиты налоговых платежей")
        page = ApplicationCashFlowRequisitesTaxPaymentsPage(self.driver)
        page.taxpayer_status('value')
        page.tax_period('value')
        page.is_tax('value')
        page.kbk('value')
        page.tax_bill_number('value')
        page.oktmo('value')
        page.tax_bill_date('value')
        page.reason_for_payment('value')
        page.click_by_text("Уполномоченные лица")
        page = ApplicationCashFlowPage(self.driver)
        page.chief('value')
        page.accountant_general('value')
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_payment_order_arrival(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page = PaymentOrderArrivalPage(self.driver)
        page.click_by_text("Платежное поручение (приход средств)")
        page.select_month("Январь", "2018")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page.document_number('value')
        page.recipient_account_details('value')
        page.operation('value')
        page.entry_date('value')
        page.drawee('value')
        page.drawee_account_details('value')
        page.tracking_number('value')
        # Реквизиты документа
        page.click_by_text("Реквизиты документа")
        page.currency('value')
        page.document_kind('value')
        page.act('value')
        page.payment_purpose('value')
        page.is_employee('value')
        page.department_unit('value')
        page.purchasing_notice('value')
        page.notification_number('value')
        page.payment_form('value')
        # Расшифровка поручения
        page.click_by_text("Расшифровка поручения")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = PaymentOrderArrivalBlankPage(self.driver)
        page.kbk('value')
        page.operation('value')
        page.kosgu('value')
        page.cost_element('value')
        page.department_unit('value')
        page.act('value')
        page.imprest_foundation('value')
        page.vat_percent('value')
        page.amount('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        # Реквизиты налоговых платежей
        page.click_by_text("Реквизиты налоговых платежей")
        page = PaymentOrderArrivalRequisitesPage(self.driver)
        page.taxpayer_status('value')
        page.kbk('value')
        page.oktmo('value')
        page.tax_period('value')
        page.tax_bill_number('value')
        page.tax_bill_date('value')
        page.reason_for_payment('value')
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_return_request(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Заявка на возврат")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = ReturnRequestPage(self.driver)
        page.document_number("value")
        page.document_date("value")
        page.account_details("value")
        page.recepient('value')
        page.ofk_registration_number("value")
        page.entry_date("value")
        page.operation("value")
        page.recepient_account_details("value")
        page.document_kind('value')
        # Расшифровка заявки
        page.click_by_text("Расшифровка заявки")
        page.kbk("value")
        page.kosgu("value")
        page.amount('value')
        page.nds_percent('value')
        page.kbk_type('value')
        page.cost_element('value')
        page.type_funds_for_return('value')
        # Дополнительные реквизиты
        page.goal_code('value')
        page.oktmo('value')
        page.department('value')
        page.investment_program('value')
        page.expenditure_goal_act('value')
        # Информация о платеже
        page.priority_of_payment('5')
        page.payment_purpose('Назначение платежа - тест')
        page.payment_type('4 – срочно')
        # Документ-основание+Реквизиты получателя
        page.document_foundation_kind('value')
        page.document_foundation_number('value')
        page.document_foundation_date('value')
        page.recepient_kbk('value')
        page.recepient_oktmo('value')
        # Документ по зачислению невыясненного платежа
        page.click_by_text("Документ по зачислению невыясненного платежа")
        page.outstanding_payment_document_number('value')
        page.outstanding_payment_document_date('value')
        page.outstanding_payment_document_amount('value')
        page.outstanding_payment_document_inn('value')
        page.outstanding_payment_document_kpp('value')
        # Уполномоченные сотрудники
        page.click_by_text("Уполномоченные сотрудники")
        page.chief('value')
        page.chief_accountant('value')
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_notification_of_the_type_and_payment_type(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Уведомления об уточнении вида и принадлежности платежа")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = NotificationTypeAndPaymentTypePage(self.driver)
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.account_details('value')
        page.activity_kind('value')
        page.budget_commitment_info_number('value')
        page.notification_kind('value')
        page.unit('value')
        # Реквизиты документа
        page.click_by_text("Реквизиты документа")
        page.counterparty('value')
        page.counterparty_account_details('value')
        page.federal_treasury_request_number('value')
        page.federal_treasury_request_date('value')
        page.region('value')
        page.is_employee('value')
        page.employee('value')
        page.passport('value')
        # Уполномоченные лица
        page.click_by_text("Уполномоченные лица")
        page.chief('value')
        page.contractor('value')
        page.contractor_phone('value')
        # Реквизиты платежного документа
        page.click_by_text("Реквизиты платежного документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = NotificationTypeAndPaymentTypeNotificationPage(self.driver)
        page.order_number('value')
        page.amount('value')
        page.operation('value')
        page.document_type('value')
        page.document_number('value')
        page.document_date('value')
        page.billing_document('value')
        page.document_foundation('value')
        page.recepient('value')
        page.recepient_name('value')
        page.recepient_account_details('value')
        page.inn('value')
        page.kpp('value')
        page.oktmo('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.statement_analysis_code('value')
        page.purpose_code('value')
        page.purpose_payment('value')
        page.comment('value')
        # Изменение реквизитов
        page.click_by_text("Добавить", 2)
        page = NotificationTypeAndPaymentTypeImagePage(self.driver)
        page.amount('value')
        page.recepient('value')
        page.recepient_account_details('value')
        page.inn('value')
        page.kpp('value')
        page.oktmo('value')
        page.recepient_personal_account('value')
        page.is_taxes('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.recepient_kbk('value')
        page.activity_kind('value')
        page.purpose_code('value')
        page.statement_analysis_code('value')
        page.purpose_payment('value')
        page.click_by_text("Сохранить", 3)
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_basis_for_reporting_amounts(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Основание для выдачи подотчетных сумм")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = BasisForReportingAmountsPage(self.driver)
        sleep(5)
        # page.number("1")
        page.document_date('value')
        page.document_kind('value')
        page.employee('value')
        page.position('value')
        page.department('value')
        page.trip_start_date('value')
        page.trip_end_date('value')
        page.checker.check_text_input('tripDays', 'value')
        page.comment('value')
        page.trip_route('value')
        # добавление строки документа
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = BasisForReportingAmountsAddLinePage(self.driver)
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.employee('value')
        page.position('value')
        page.amount('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        # добавление копии строки документа
        page.table_select_row_click('value')
        page.click_by_text("Добавить")
        page.click_by_text("Копию строки")
        sleep(3)
        page.table_select_row_click('value', order=2)
        page.click_by_text("Открыть")
        page = BasisForReportingAmountsAddLinePage(self.driver)
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.employee('value')
        page.position('value')
        page.amount('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Сохранить")

    def test_advance_report(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Авансовый отчет")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = AvansReportPage(self.driver)
        page.document_kind('value')
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.employee('value')
        page.position('value')
        page.department('value')
        page.employee_full_name('value')
        page.document_foundation('value')
        page.purpose('value')
        page.comment('value')
        # добавление копии строки документа
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = AvansReportAddLinePage(self.driver)
        page.operation_master('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.document_date('value')
        page.document_number('value')
        page.amount('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Связанные документы")
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def te1st_payment_order_through_contract_with_the_supplier(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page = ContractWithSupplierPage(self.driver, 5)
        page.select_month("Январь", "2018")
        page.click_by_text("Договор с поставщиком")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page.document_type("Договор")
        page.number('value')
        page.date('value')
        sleep(4)
        page.counter_party('value')
        page.bank_account_number('value')
        page.uin("value")
        page.currency("value")
        # вкладка  Условия договора
        page.click_by_text("Условия договора")
        page.personal_account('value')
        page.payment_type("value")
        page.budget_commitment('value')
        page.payment_against_invoice('value')
        page.date_begin("10.01.2018")
        page.date_end("10.11.2018")
        page.security_type('value')
        page.security_amount('value')
        page.security_period('value')
        page.sending_letter_number('value')
        page.assurance_register_record_number('value')
        page.letter_date('value')
        page.note("value")
        page.responsible('value')
        page.department_unit('value')
        page.penalty_period('value')
        page.penalty_percent('value')
        page.penalty_amount('value')
        page.subject_contract("value")
        page.payment_terms("value")
        page.prolongation_term('value')
        sleep(1)
        # Вкладка Детализация по КБК
        page.click_by_text("Детализация по КБК")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = ContractWithSupplierDetailKBKPage(self.driver)
        page.financial_year('value')
        page.entry_date('value')
        page.changed('value')
        page.operation('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_element('value')
        page.contract_subject('value')
        page.department('value')
        page.budgetary_plan_act('value')
        page.investment_program('value')
        page.department_unit('value')
        page.work('value')
        page.amounts_amount('value')
        page.amounts_nds_percent('value')
        page.advance('value')
        page.checker.check_text_input("amountsAmountWithoutNds", 'value')
        page.click_by_text("Сохранить", 2)
        # Вкладка Детализация по ОКПД2
        page.click_by_text("Детализация по ОКПД2")
        page.click_by_text("Добавить", 2)
        page = ContractWithSupplierDetailOKPDPage(self.driver)
        page.order_number('value')
        page.okpd2('value')
        page.unit_of_measure('value')
        page.unit_price('value')
        page.quantity('value')
        page.amount('value')
        page.purchase_object_type('value')
        page.click_by_text("Сохранить", 2)
        # Вкладка Сведения о госконтракте
        page.click_by_text("Сведения о госконтракте")
        page = InformationAboutContractPage(self.driver)
        page.aviso('value')
        page.purchase_identity('value')
        page.register_record_number('value')
        page.registration_date('value')
        page.privacy('value')
        page.confirm_document_number('value')
        page.confirm_document_date('value')
        page.confirm_document_kind('value')
        page.comment('value')
        page.department('value')
        page.auction_date('value')
        page.declared_value('value')
        page.change_foundation('value')
        page.for_small_entrepreneur('value')
        page.domestic_goods_preference('value')
        page.perfomance_document_number('value')
        page.contract_performance_date('value')
        page.terminated_by('value')
        page.contract_cancellation_record_number('value')
        page.contract_perfomance_foundation('value')
        # Вкладка История изменений
        page.click_by_text("История изменений")
        page.click_by_text("Добавить", 3)
        page = HistoryPage(self.driver)
        page.change_date('value')
        page.change_number('value')
        page.change_type('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        # Вкладка Календарный план
        page.click_by_text("Календарный план")
        page.click_by_text("Добавить", 4)
        page = CalendarPlanPage(self.driver)
        page.financial_year('value')
        page.work_name('value')
        page.result('value')
        page.comment('value')
        page.start_date('value')
        page.end_date('value')
        page.amount('value')
        page.click_by_text("Сохранить", 2)
        # Вкладка Дополнительные контрагенты
        page.click_by_text("Дополнительные контрагенты")
        page.click_by_text("Добавить", 5)
        page.counterparty('value')
        page.account_details('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Сканы документов")
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_ensuring_fulfillment_of_obligations(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Обеспечение исполнения обязательств")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = EnsuringFulfillmentOfObligationsPage(self.driver)
        page.document_number('value')
        page.document_date('value')
        page.operation('value')
        page.counterparty('value')
        page.entry_date('value')
        page.retirement_date('value')
        page.amount('value')
        page.guarantor('value')
        page.assurance_starts('value')
        page.assurance_ends('value')
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_information_about_budget_obligation(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Сведения о бюджетном обязательстве ")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = InformationAboutBudgetObligationPage(self.driver)
        page.document_number('value')
        page.document_date('value')
        page.financial_year('value')
        page.liability('value')
        # Вкладка
        page.tracking_number('value')
        page.registration_date('value')
        page.account_details('value')
        page.guid('value')
        page.counterparty('value')
        page.transaction_account('value')
        page.chief('value')
        page.prepared_by('value')
        # Расшифровка обязательства
        page.click_by_text("Расшифровка обязательства")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = InformationAboutBudgetObligationAddLinePage(self.driver)
        page.financial_year('value')
        page.kbk('value')
        page.kosgu('value')
        page.activity_kind('value')
        page.kbk_type('value')
        page.comment('value')
        page.investment_program('value')
        # Суммы на текущий год
        page.current_year_amounts('value')
        page.february('value')
        page.march('value')
        page.april('value')
        page.may('value')
        page.june('value')
        page.july('value')
        page.august('value')
        page.september('value')
        page.october('value')
        page.november('value')
        page.december('value')
        # Суммы на плановый период
        page.first_year_amount('value')
        page.second_year_amount('value')
        page.third_year_amount('value')
        page.other_years_amount('value')
        # Суммы прошлых лет
        page.completed_amout('value')
        page.not_completed_amount('value')
        page.conditional_payment('value')
        page.analytical_code('value')
        page.act('value')
        page.payment_day('value')
        page.click_by_text("Сохранить", 2)
        # История изменений
        page.click_by_text("История изменений")
        page.click_by_text("Добавить")
        page = InformationAboutBudgetObligationHistoryPage(self.driver)
        page.change_number('value')
        page.change_date('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        # Реквизиты документа-основания
        page.click_by_text("Реквизиты документа-основания")
        page = InformationAboutBudgetObligationRequisitesPage(self.driver)
        page.document_foundation_kind('value')
        page.document_foundation_number('value')
        page.document_foundation_date('value')
        page.document_fondation_currency('value')
        page.amount('value')
        page.currency_amount('value')
        page.advance_percent('value')
        page.advance_amount('value')
        page.register_record_number('value')
        page.document_foundation_subject('value')
        # Дополнительные контрагенты
        page.click_by_text("Дополнительные контрагенты")
        page.click_by_text("Добавить")
        page = InformationAboutBudgetObligationDopPage(self.driver)
        page.counterparty('value')
        page.account_details('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_invoice_from_the_supplier(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Счет от поставщика")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = InvoiceFromTheSupplierPage(self.driver)
        page.document_number('value')
        page.document_date('value')
        page.paid_date('value')
        page.entry_date('value')
        page.operation('value')
        page.department_unit('value')
        page.supplier('value')
        page.supplier_account_detail('value')
        page.account_details('value')
        page.department("Департамент внешних коммуникаций")
        page.note('value')
        sleep(4)
        # Добавляем документ счет от поставщика строку
        page = InvoiceFromTheSupplierAddLinePage(self.driver)
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page.kbk('value')
        page.kosgu('value')
        page.cost_element("value")
        page.act('value')
        page.okpd2('value')
        page.comment("value")
        page.amount("value")
        page.vat_percent('value')
        page.checker.check_text_input("amountWithoutNds", "value", 2)
        page.checker.check_text_input("ndsAmount", "value", 2)
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_invoice_from_vendor(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Счет-фактура от поставщика")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = InvoiceFromVendorPage(self.driver)
        page.document_kind('value')
        page.document_number('value')
        page.document_date('value')
        page.received_date('value')
        page.correction_number('value')
        page.correction_date('value')
        page.editable('value')
        page.vendor('value')
        page.billing_type('value')
        page.nds_operation_code('value')
        page.public_contract_identifier('value')
        page.mercantile_agent('value')
        page.employee('value')
        page.department_unit('value')
        page.trip('value')
        page.operation('value')
        page.entry_date('value')
        page.capitalization_date('value')
        page.comment('value')
        # Счет-фактура от поставщика - добавление строки
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = InvoiceFromVendorAddLinePage(self.driver)
        page.goods_name('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_elements('value')
        page.act('value')
        page.unit_of_measure('value')
        page.quantity('value')
        page.price('value')
        page.nds_percent('value')
        page.amount('value')
        page.excise_duty('value')
        page.cargo_custom_declaration('value')
        page.origin_country('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")

    def test_incoming_act(self):
        page = MenuPage(self.driver)
        page.click_to_eagle()
        page.select_month("Январь", "2018")
        page.click_by_text("Акт входящий")
        page.click_by_text("Добавить")
        page.click_by_text("Новый документ")
        page = IncomingActPage(self.driver)
        page.document_kind('value')
        page.document_number('value')
        page.document_date('value')
        page.entry_date('value')
        page.contractor('value')
        page.department_unit('value')
        page.comment('value')
        # Акт входящий - добавление строки
        page.click_by_text("Строки документа")
        page.click_by_text("Добавить")
        page.click_by_text("Новую строку")
        page = IncomingActAddLinePage(self.driver)
        page.operation('value')
        page.kbk('value')
        page.kosgu('value')
        page.cost_elements('value')
        page.nds_percent('value')
        page.amount('value')
        page.advance_offset('value')
        page.under_repair('value')
        page.comment('value')
        page.click_by_text("Сохранить", 2)
        page.click_by_text("Проводки")
        page.click_by_text("Сохранить")
        page.click_by_text("Закрыть")


